
default: &default
  adapter: postgresql
  encoding: unicode

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: zhouxin
  password: 123456

development:
  <<: *default
  database: pet_api_development


test:
  <<: *default
  database: pet_api_test

production:
  <<: *default
  database: pet_api_production
  username: pet_api
  password: <%= ENV['PET_API_DATABASE_PASSWORD'] %>
